### ISSUE TITLE
Enhancement: Correct error handling

### ISSUE THREAD

**Issue by San7o** [Vortex-Linux/ship#11]
## Description

Whenever the application calls system() to run a command on the host machine, the return value is never checked. This leads to confusing output where the command would fail with an error message but the application would print "success".

## What to do

The application should always check the return value of system() and display a correct output. 

Example of bad output:

![Pasted image 20240819175334](https://github.com/user-attachments/assets/972fea53-dc35-486a-a225-2df86c6b5852)

**Comment by arungeorgesaji** [comment]
This issue has been fixed as of the latest commit,a function named system_exec() has been added which checks if the command ran  successfully with system(),this function replaces all the normal system() calls except a few ones which require special requirements
