### ISSUE TITLE
Security: Unnecessary elevated permissions

### ISSUE THREAD

**Issue by San7o** [Vortex-Linux/ship#12]
## Problem

The current application uses "sudo" commands to interact with the vms when using "virsh" in std::system(). This is unnecessary if the user is in the group "libvirt".

## Solution
I am proposing to check if the user is in the group at the start of the application and to drop "sudo" from all commands.

### Discussion
I may be wrong about this, but as far as I know and for what I tested, you don't need sudo privileges.

**Comment by arungeorgesaji** [comment]
According to the tests i have performed not having the elevated privileges causing a lot of issues even if the user is added to the virsh group,will do further testing and see if I can make it work with the base permissions

**Comment by arungeorgesaji** [comment]
@San7o After testing around a little bit i found a few issues when i tried to implement this with the bridges and networking parts,would love your view on the current code and how it does and to see if anything is done in a not so correct way which is causing the issue.

Latest coding is in the development branch

**Comment by arungeorgesaji** [comment]
Update: After a bit more testing around I found that if i run qemu system instead of session,the problem can be solve,will be closing this issue and will be pushing the updated code
